### ISSUE TITLE
HTTPS support for WinRM

### ISSUE THREAD

**Issue by arnos** [cloudsoft/winrm4j#16]
I'm not sure if this is the right place to post this as an issue. As this boils back to Brooklyn, but there seems to be no active or closed issue in Jira.

On http://brooklyn.apache.org/v/latest/yaml/winrm/index.html it is mentioned "In future we aim to improve Brooklyn to support HTTPS." --> which, I assume, is one of the reasons that gave birth to winrm4j.

Two part question really:
- what is the status?
- what can be done to help?

**Comment by neykov** [comment]
Hi @arnos, we are currently in the process of switching the library to use Apache CXF (see https://github.com/cloudsoft/winrm4j/pull/12) which will give us more control over the http layer.  Once the PR is merged it will be fairly easy to add `https` support and it is something we are looking into. All improvements to the library will feed back into Brooklyn.

The current version of the library should support https as well, but it is not something we have tested yet as as it's not enabled out of the box on stock Windows images - that's another reason for the above PR. It will allow Brooklyn to login and enable https for existing setups.

You can try https right now:
  * Enable https on the windows server and let the port through the firewall. Basic authentication needs to be enabled as well.
  * Set the full url, including https protocol, of the WinRM service in the address config - `https://windows.host:5986/wsman`
  * Since https usually uses self-signed certificates you'll have to allow that explicitly. You need one of:
    * Import the self signed certificate into the java trust store.
    * [Accept the certificate with some Java code](http://stackoverflow.com/questions/875467/java-client-certificates-over-https-ssl/876785#876785).

We will appreciate if you share the results from testing your setup.

**Comment by arnos** [comment]
Sorry for the long delay, we got side tracked. 

Thanks @neykov for the update

I've tested winrm4j 0.2.0 using both import and the disabling the SSL. And it worked out of the box.

**Comment by neykov** [comment]
That's great news @arnos, thanks for testing it out.
