### ISSUE TITLE
Missing Shell message part on Windows 2008

### ISSUE THREAD

**Issue by semancik** [cloudsoft/winrm4j#69]
winrm4j fails with windows 2008 because they are not sending Shell message part for Create operation.
The patch is here:
https://github.com/Evolveum/winrm4j/commit/752dd774410d9de5ab40d5fb909778e9b9e09303
However, it also requires CXF patch:
https://github.com/Evolveum/cxf/commit/8334de839db49bd16c9c33aade31d5a618cadd09

**Comment by neykov** [comment]
Glad to see you around @semancik.
That's been handled on master now, in a similar way to your patch (see [WinRmClient.getShellId()](https://github.com/cloudsoft/winrm4j/blob/master/client/src/main/java/io/cloudsoft/winrm4j/client/WinRmClient.java#L343). Instead of patching CXF I'm patching the response with a `SOAPHandler` in [`StripShellResponseHandler`](https://github.com/cloudsoft/winrm4j/blob/master/client/src/main/java/io/cloudsoft/winrm4j/client/StripShellResponseHandler.java). 
I've pinged the CXF guys for this one, but they couldn't come up with a better solution.

**Comment by aledsage** [comment]
The fix form @neykov, which has been in master for a while, will be in the latest release: 0.6.1. Therefore closing this issue - please shout and reopen if you think it is still an issue!
